enum EventName {
  userDataEvent,
  loginPageLoadedEvent,
  loginPageExitEvent,
  loginWithSocialClickedEvent,
  socialSignUpCompletedEvent,
  socialLoginStartedEvent,
  socialLoginCompletedEvent,
  socialLoginFailedEvent,
  emailLoginStartedEvent,
  emailEnteredEvent,
  emailValidationFailedEvent,
  passwordEnteredEvent,
  passwordValidationFailedEvent,
  loginButtonClickedEvent,
  userLoginCompletedEvent,
  userLoginFailedEvent,
  //userSignUpFailedEvent,
  userAccountActivatedEvent,
  forgetPasswordClickedEvent,
  searchPerformedEvent,
  searchResultClickedEvent,
  searchResultAbandonedEvent,
  searchResultFilterAppliedEvent,
  searchResultSortedEvent,
  searchSuggestionSelectedEvent,
  searchPageViewedEvent,
  searchPageExitedEvent,
  categoryClickedEvent,
  aboutAlmentorClickedEvent,
  helpAndSupportClickedEvent,
  languageChangedEvent,
  termsAndConditionsClickedEvent,
  privacyPoliciesClickedEvent,
  logoutClickedEvent,
  logoutConfirmedEvent,
  logoutCanceledEvent,
  myCertificateAccessedEvent,
  aboutUsViewedEvent,
  helpAndSupportDialogOpenedEvent,
  myLearningPageOpenedEvent,
  courseResumedEvent,
  courseDetailsViewedEvent,
  courseSearchEvent,
  savedCourseAddedEvent,
  completedCourseCardViewedEvent,
  courseCompletionMarkedEvent,
  savedCourseRemovedEvent,
  courseCardClickedEvent,
  courseLessonResumedEvent,
  courseSavedEvent,
  courseEnrollmentStartedEvent, // should be deleted new release
  courseEnrollmentEvent,
  //userSignUpStartedEvent,
  userSignUpCompletedEvent,
  appDataDeviceTypeEvent,
  appDataDeviceModelEvent,
  appDataAppVersionEvent,
  appDataPageViewsEvent,
  appDataAppInstalledEvent,
  appDataAppUninstalledEvent,
  userDataUserTypeEvent,
  userDataUserNameEvent,
  userDataUserEmailEvent,
  userDataSignUpDateEvent,
  userDataPhoneEvent,
  userDataGenderEvent,
  userDataIsSubscribedEvent,
  userDataEndSubscriptionDateEvent,
  userDataFirstSubscriptionDateEvent,
  addToCartEvent,
  paymentMethodSelectedEvent,
  subscriptionPlanSelectedEvent,
  couponCodeSubmittedEvent,
  subscriptionCheckoutEvent,
  paymentCompletedEvent,
  paymentStatusSuccessEvent,
  paymentStatusFailEvent,
  paymentStatusPendingEvent,
  plansPageViewedEvent,
  subscriptionCheckoutStartedEvent,
  subscriptionPlanChangedEvent,
  paymentCancelledEvent,

  /// Clips
  clipsTabOpenedEvent,
  clipServedEvent,
  clipErrorEvent,
  clipWatchedEvent,
  clipCompletedEvent,
  clipLikedEvent,
  clipCtaClickedEvent,
  clipSharedEvent,
  microLearnButtonClicked,
  signupBlockerOpenedEvent,
  signupBlockerClosedEvent,
  signupBlockerCTAClickedEvent,

  /// Downloads
  courseDownloadInitiatedEvent,
  courseDownloadCompletedEvent,
  lessonDownloadInitiatedEvent,
  lessonDownloadCompletedEvent,
  courseDownloadStoppedEvent,
  downloadedCourseDeletedEvent,
  downloadedCoursePlayedEvent,
  downloadSettingsChangedEvent,
  downloadsExpiredEvent,
  expiredDownloadActivatedEvent,
  downloadsErrorEvent,
  searchInitiatedEvent,
  hasPipFeatureEvent,
  pipEnterdEvent,
  pipExitedEvent,
  certificateAddedToLinkedin,
  freeLessonPlayed,
  contentPageViewed,

  //authentication events
  getStartedPageEnteredEvent,
  continueWithSocialClickedEvent,
  continueWithEmailClickedEvent,
  userSignupStartedEvent,
  signupDetailsSubmittedEvent,
  userSignUpFailedEvent,
  userSignupCompletedEvent,
  passwordResetInstructionsSentEvent,
  userLoginStartedEvent,

  // AI Chat Events
  almentorAiChatEnteredEvent,
  almentorAiChatQuerySentEvent,
  almentorAiChatRecommendationProvidedEvent,
  almentorAiChatNewChatStartedEvent,
  continueWithPhoneClickedEvent,

  // Experiment events
  discoverMoreClickedEvent,
  appOpenedEvent,

  // New Course promo page
  promoOpened,
  videoPlayed,
  videoPaused,
  videoEnded,
  videoProgress,
  videoError,
  videoEnterFullScreen,
  subscribeUnauthenticatedEvent,
  subscribeNowEvent,
  courseSharedEvent,
  courseCompletedEvent,

  // New Course details page
  lessonStarted,
  lessonCompleted,
  notesAdded,
  savedNoteClicked, // should be deleted new release
  notePlayVideoClicked,
  noteDeleted,
  globalNotesOpened, // should be deleted new release
  notesPagedOpened,
  attachmentDownload,
  attachmentOpened,
  globalAttachmentOpened, // should be deleted new release
  attachmentPagedOpened,
  lessonSaved,
  lessonUnsaved,
  savedLessonOpened,
  globalSavedLessonsOpened, // should be deleted new release
  savedLessonPagedOpened,
  progressMilestoneShown,
  audioModeOpened,
  audioModeClosed,
}
