enum EventName {
  userDataEvent,

  loginPageLoadedEvent,
  loginPageExitEvent,
  loginWithSocialClickedEvent,
  socialSignUpCompletedEvent,
  socialLoginStartedEvent,
  socialLoginCompletedEvent,
  socialLoginFailedEvent,
  emailLoginStartedEvent,
  emailEnteredEvent,
  emailValidationFailedEvent,
  passwordEnteredEvent,
  passwordValidationFailedEvent,
  loginButtonClickedEvent,
  userLoginCompletedEvent,
  userLoginFailedEvent,
  //userSignUpFailedEvent,
  userAccountActivatedEvent,
  forgetPasswordClickedEvent,
  searchPerformedEvent,
  searchResultClickedEvent,
  searchResultAbandonedEvent,
  searchResultFilterAppliedEvent,
  searchResultSortedEvent,
  searchSuggestionSelectedEvent,
  searchPageViewedEvent,
  searchPageExitedEvent,
  categoryClickedEvent,
  aboutAlmentorClickedEvent,
  helpAndSupportClickedEvent,
  languageChangedEvent,
  termsAndConditionsClickedEvent,
  privacyPoliciesClickedEvent,
  logoutClickedEvent,
  logoutConfirmedEvent,
  logoutCanceledEvent,
  myCertificateAccessedEvent,
  aboutUsViewedEvent,
  helpAndSupportDialogOpenedEvent,
  myLearningPageOpenedEvent,
  courseResumedEvent,
  courseDetailsViewedEvent,
  courseSearchEvent,
  savedCourseAddedEvent,
  completedCourseCardViewedEvent,
  courseCompletionMarkedEvent,
  savedCourseRemovedEvent,
  courseCardClickedEvent,
  courseLessonResumedEvent,
  courseSavedEvent,
  courseEnrollmentStartedEvent,
  //userSignUpStartedEvent,
  userSignUpCompletedEvent,
  appDataDeviceTypeEvent,
  appDataDeviceModelEvent,
  appDataAppVersionEvent,
  appDataPageViewsEvent,
  appDataAppInstalledEvent,
  appDataAppUninstalledEvent,
  userDataUserTypeEvent,
  userDataUserNameEvent,
  userDataUserEmailEvent,
  userDataSignUpDateEvent,
  userDataPhoneEvent,
  userDataGenderEvent,
  userDataIsSubscribedEvent,
  userDataEndSubscriptionDateEvent,
  userDataFirstSubscriptionDateEvent,
  addToCartEvent,
  paymentMethodSelectedEvent,
  subscriptionPlanSelectedEvent,
  couponCodeSubmittedEvent,
  subscriptionCheckoutEvent,
  paymentCompletedEvent,
  paymentStatusSuccessEvent,
  paymentStatusFailEvent,
  paymentStatusPendingEvent,
  plansPageViewedEvent,
  subscriptionCheckoutStartedEvent,
  subscriptionPlanChangedEvent,

  /// Clips
  clipsTabOpenedEvent,
  clipServedEvent,
  clipErrorEvent,
  clipWatchedEvent,
  clipCompletedEvent,
  clipLikedEvent,
  clipCtaClickedEvent,
  clipSharedEvent,
  signupBlockerOpenedEvent,
  signupBlockerClosedEvent,
  signupBlockerCTAClickedEvent,

  /// Downloads
  courseDownloadInitiatedEvent,
  courseDownloadCompletedEvent,
  lessonDownloadInitiatedEvent,
  lessonDownloadCompletedEvent,
  courseDownloadStoppedEvent,
  downloadedCourseDeletedEvent,
  downloadedCoursePlayedEvent,
  downloadSettingsChangedEvent,
  downloadsExpiredEvent,
  expiredDownloadActivatedEvent,
  downloadsErrorEvent,

  searchInitiatedEvent,
  hasPipFeatureEvent,

  pipEnterdEvent,
  pipExitedEvent,

  certificateAddedToLinkedin,
  freeLessonPlayed,

  contentPageViewed,

  //authentication events
  getStartedPageEnteredEvent,
  continueWithSocialClickedEvent,
  continueWithEmailClickedEvent,
  userSignupStartedEvent,
  signupDetailsSubmittedEvent,
  userSignUpFailedEvent,
  userSignupCompletedEvent,
  passwordResetInstructionsSentEvent,
  userLoginStartedEvent,
  continueWithPhoneClickedEvent,

  // AI Chat Events
  almentorAiChatEnteredEvent,
  almentorAiChatQuerySentEvent,
  almentorAiChatRecommendationProvidedEvent,
  almentorAiChatNewChatStartedEvent,
}
